services:
  db:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: unsis_smile
    ports:
      - "3306:3306" # Base de datos
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - unsismile_network

networks:
  unsismile_network:
    driver: bridge

volumes:
  mysql_data:
  gradle_cache: