version: '3.8'

services:
  app:
    container_name: unsismile_back-app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: "mariadb:10.5"
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=unsis_smile
    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 
    external: false