services:
  app:
    container_name: unsismile_back-app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - gradle_cache:/home/gradle/.gradle  # Caché de dependencias de Gradle

  db:
    image: "mariadb:10.5"
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=unsis_smile
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # Volumen para persistir los datos de MySQL

volumes:
  mysql_data:
    external: false
  gradle_cache:  # Volumen para caché de Gradle
    external: false