services:
  app:
    container_name: unsismile_back-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082" # El puerto del host apunta al puerto del contenedor
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/unsis_smile?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&useTimezone=true&serverTimezone=America/Mexico_City&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.mariadb.jdbc.Driver
      JWT_SECRET: 
      CORS_ALLOWED_ORIGINS: http://localhost:8081
      CORS_ALLOWED_METHODS: GET,POST,PUT,PATCH,DELETE,OPTIONS
      MAX_MEDICAL_RECORD_NUMBER: 3 # Número de inicio de expediente médico


      FILES_URI: http://localhost:8082/unsismile/api/v1/files/file/

      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USERNAME: example@gmail.com
      MAIL_PASSWORD: example
      MAIL_SSL_TRUST: smtp.gmail.com
    networks:
      - unsismile_network
    volumes:
      - gradle_cache:/home/gradle/.gradle
      - ./logs:/var/log/unsismile    # Agregar este volumen

  db:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: unsis_smile
    ports:
      - "3306:3306" # Base de datos
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - unsismile_network

networks:
  unsismile_network:
    driver: bridge

volumes:
  mysql_data:
  gradle_cache: