package edu.mx.unsis.unsiSmile.repository.medicalHistories;

import edu.mx.unsis.unsiSmile.model.medicalrecords.dentalprophylaxis.ProphylaxisToothConditionAssignmentModel;
import edu.mx.unsis.unsiSmile.model.medicalrecords.dentalprophylaxis.ProphylaxisToothConditionAssignmentId;
import org.springframework.data.jpa.repository.JpaRepository;

public interface IProphylaxisToothConditionAssignmentRepository extends JpaRepository<ProphylaxisToothConditionAssignmentModel, ProphylaxisToothConditionAssignmentId> {
}
