package edu.mx.unsis.unsiSmile.repository.medicalrecords.dentalprophylaxis;

import edu.mx.unsis.unsiSmile.model.medicalrecords.dentalprophylaxis.ProphylaxisToothfaceConditionsAssignmentModel;
import edu.mx.unsis.unsiSmile.model.medicalrecords.dentalprophylaxis.ProphylaxisToothFaceConditionAssignmentId;
import org.springframework.data.jpa.repository.JpaRepository;

public interface IProphylaxisToothfaceConditionsAssignmentRepository extends JpaRepository<ProphylaxisToothfaceConditionsAssignmentModel, ProphylaxisToothFaceConditionAssignmentId> {
}
